### ISSUE TITLE
Build the profile data

### ISSUE THREAD

**Issue by nirgn975** [nirgn975/InsurancePensionHackathon#17]
We need to have a header with 3 types of data (like in the paper).
Every one of them should contain a component (let's call that component `bar-chart`).
That component will be dumb and only receive the data as an `@input` and will display the chart.

The chart is: https://bl.ocks.org/mbostock/2368837 (you don't need to play with it in this issue, just place it).

The data should look like: https://bl.ocks.org/mbostock/2368837#data.tsv (create a `data.json` file in the `assets` directory with that data).

**Comment by DavidBronfen** [comment]
Npm installed, runing the server and getting this error:
<img width="1212" alt="hyper" src="https://user-images.githubusercontent.com/12427216/32178836-6f992a58-bd96-11e7-82b8-630a1576e0da.png">
