### ISSUE TITLE
Create a registration and login components.

### ISSUE THREAD

**Issue by nirgn975** [nirgn975/InsurancePensionHackathon#3]
Registration should contain:
- [x] ID.
- [x] Password.
- [x] Confirm password.
- [x] Credit card number.
- [x] Credit card CVV.
- [x] Credit card month and year.

Login should login:
- [x] ID.
- [x] Password.

In this issue just HTML & CSS.

**Comment by PrajapatiAnkit** [comment]
can i make these component in html,css??

**Comment by nirgn975** [comment]
@PrajapatiAnkit HTML and CSS in Angular (4), But @DavidBronfen already assignee to this issue, so I don't think it a good idea to do this.

**Comment by PrajapatiAnkit** [comment]
ok
