### ISSUE TITLE
Login Event

### ISSUE THREAD

**Issue by nirgn975** [nirgn975/InsurancePensionHackathon#5]
- [ ] Dispatch an action when the user click on the login `submit` button.

Those actions should be catch by the `effect` and should call a `service` (that should not do anything for now), and it should save the data in the `store`.

**Comment by kushboojain** [comment]
Will work on it

**Comment by nirgn975** [comment]
@kushboojain It's already assignee to @DavidBronfen so I don't it's a good idea to work on this issue.
